version: '3.6'

services:
  # This time, our webserver is a Flask application written in Python
  web:
    # 1. Lets build our custom Docker image!
    
    # Bind mount our source directory
    volumes:
      # 4. No code = no application.
      # Create a bind mount from "./src" to "/code"!
    # And ports... again!
    ports:
      - 8000:5000
    networks:
      - view_counter_network
  # Redis - high performance key-value store
  # Default configuration is port 6379
  redis:
    image: redis:alpine
    # 2. Seems like web and Redis are not in the same network...

networks:
  view_counter_network:
