version: '3.6'

services:
  web:
    # Image to use
    image: caddy:latest
    working_dir: /var/www/html
    # 1. We're missing the "file-server" argument, for the command. Add it!

    # 2. Map port 80 in container to port 8080 on host

    # 3. Bind mount the index.html to /var/www/html
