FROM --platform=amd64 caddy:2.5.2-alpine

RUN mkdir /var/www/html

# TODO: Copy index.html to /var/www/html/index.html
...

# TODO: Change workdirectory /var/www/html directory
...

CMD ["caddy", "file-server"]
