FROM --platform=amd64 caddy:2.7.4-alpine

RUN mkdir -p /var/www/html

# TODO: Copy index.html to /var/www/html/index.html
COPY ./index.html /var/www/html/index.html


# TODO: Change workdirectory /var/www/html directory
WORKDIR /var/www/html

CMD ["caddy", "file-server"]
